# Meson cross-compilation configuration for pango.wasm
# Text layout engine with complex dependencies
# Copyright 2025 Superstruct Ltd, New Zealand

[binaries]
c = 'emcc'
cpp = 'em++'
ar = 'emar'
strip = 'emstrip'
objcopy = 'emstrip'
ld = 'emcc'
exe_wrapper = 'node'
pkg-config = 'pkg-config'

[properties]
needs_exe_wrapper = true
c_args = [
  '-s', 'WASM=1',
  '-s', 'USE_PTHREADS=0',
  '-DPANGO_ENABLE_BACKEND',
  '-DPANGO_ENABLE_ENGINE',
  '-DG_OS_UNIX',
  '-O3',
  '--closure', '1',
  '-flto'
]
cpp_args = [
  '-s', 'WASM=1',
  '-s', 'USE_PTHREADS=0',
  '-DPANGO_ENABLE_BACKEND',
  '-DPANGO_ENABLE_ENGINE',
  '-DG_OS_UNIX',
  '-O3',
  '--closure', '1',
  '-flto'
]
c_link_args = [
  '-s', 'WASM=1',
  '-s', 'MODULARIZE=1',
  '-s', 'EXPORT_ES6=1',
  '-s', 'INITIAL_MEMORY=128MB',
  '-s', 'MAXIMUM_MEMORY=2GB',
  '-s', 'ALLOW_MEMORY_GROWTH=1',
  '-s', 'STACK_SIZE=10MB',
  '--closure', '1',
  '-flto'
]
cpp_link_args = [
  '-s', 'WASM=1',
  '-s', 'MODULARIZE=1',
  '-s', 'EXPORT_ES6=1',
  '-s', 'INITIAL_MEMORY=128MB',
  '-s', 'MAXIMUM_MEMORY=2GB',
  '-s', 'ALLOW_MEMORY_GROWTH=1',
  '-s', 'STACK_SIZE=10MB',
  '--closure', '1',
  '-flto'
]

[host_machine]
system = 'emscripten'
cpu_family = 'wasm32'
cpu = 'wasm32'
endian = 'little'